### registerOrder
POST http://localhost:3003/order/register
Content-Type: application/json

{
    "clientName": "adeir",
    "totalPrice": 10,
    "productsPurchased": [{"id":"03e199f6-279d-49fc-9b3c-643a1be2021d","qty_purchased": 100}],
    "deliveryDate": "2022-12-31"
}

### GetAllStock
GET http://localhost:3003/stock/all

### Update Stock
PATCH http://localhost:3003/stock/update
Content-Type: application/json

{
    "productsPurchased": [{"id":"03e199f6-279d-49fc-9b3c-643a1be2021d","qty_purchased": 100},{"id":"0a204a5a-c673-426b-83a7-b0fa615975ab","qty_purchased": 150}]
}
###