### registerOrder
POST http://localhost:3003/order/register
Content-Type: application/json

{
    "clientName": "adeir",
    "totalPrice": 10,
    "productsPurchased": [{"id":"01684dbb-81aa-4943-948f-bb502d6b9710","qty_purchased": 501}],
    "deliveryDate": "2022-12-31"
}

### GetAllStock
GET http://localhost:3003/stock/all

### Update Stock
PATCH http://localhost:3003/stock/update
Content-Type: application/json

{
    "productsPurchased": [{"id":"01684dbb-81aa-4943-948f-bb502d6b9710","qty_purchased": 1000},{"id":"0c915b3a-cd81-4f26-98e6-17c9a1193e65","qty_purchased": 150}]
}

###