version: '3.1'

services:
  app:
    build: .
    command: wait-for db:3306 -t 120 -- .docker/entrypoint.sh
    # entrypoint: .docker/entrypoint.sh
    container_name: nodeAPI-Shopper
    ports:
      - 3003:3003
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: mysqkl-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    # volumes:
    #   - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
  
  dbtest:
    image: mysql
    container_name: mysqkl-dbTest
    restart: always
    tty: true
    ports:
      - 3307:3306
    # volumes:
    #   - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
